### PR TITLE
Better German translation for Loading/loaded. Maybe it should be even…

### PR DESCRIPTION
**Pull request by menkej**
… more elaborately like "Apps currently loading data" and "Apps recently loading data"?

### CODE REVIEW

**Comment by TraderStf** [comment]
find it a bit long...
I don't know is it only apps
and is it only loading (not uploading)

users knows what Loading is for

If I had to do a change it would be a more unusual name, go find "loading" app on the net, billions of sites

Something like "WhoIsLoading(.app)"... hum not terrible "whois", well you get the idea.

**Comment by derhuerst** [comment]
**+1 for this PR! Right now, the translation is completely unintuitive.** Looking up 4a0bbf1 made me understand what "Geladen" is supposed to mean.

I even find the English wording quite confusing. Can you explain the difference between the two sections in the dropdown menu?

**Comment by BonzaiThePenguin** [comment]
Loading -> apps that are using the network right now
Loaded -> apps that used the network recently

I'm going to start merging the translations now, then I'll merge some fixes and release 1.1.1.

**Comment by TraderStf** [comment]
People who download Loading App knows why...
so Loading and Loaded menu headings are ok.

In French, I made them "shorter" without even mentionning it is a "load" process.

+"LOADING" = "En cours";   ~running/active, just like in Apple Monitor Utility
+"LOADED" = "Récemment"; ~recent those who where running recently

**Comment by derhuerst** [comment]
> I'm going to start merging the translations now, then I'll merge some fixes and release 1.1.1.

Great!

> Loading -> apps that are using the network right now
> Loaded -> apps that used the network recently

I think "Right now" and "Recently" would really be a better wording.

> People who download Loading App knows why...

No. I'm one of those who read the readme, downloaded the app and still didn't exactly know what the two categories are. So I think changing the English wording as well would be a good thing.

**Comment by TraderStf** [comment]
@derhuerst I propose the same in French "Right now" and "Recently" so we agree :-)

Be careful not downloading viruses ;-)

**Comment by philippgeisler** [comment]
+1 for the need of a better German translation (I actually had opened another pull request to the same effect)

I think "Loading" for active apps would still be okay and understandable in German, if one wanted to keep the connection to the name Loading, but "Geladen" means something different ("these files/apps have been downloaded"), so that needs to be changed to be understandable IMHO. I would prefer this translation here, both "Aktiv" and "Kürzlich", though.

**Comment by BonzaiThePenguin** [comment]
We can do "Aktiv" and "Kürzlich". I'll merge it in the next version tho, getting 1.2.1 out the door right now.

**Comment by BonzaiThePenguin** [comment]
Sorry for delaying this one, there were a ton of German translations offered and they all had different solutions for how to translate things, so I made it a lower priority than the other ones. I'll look into it next.

**Pull request merged**
